name: Itachi Bot - Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been forgotten like Itachi’s past. Marking as stale."
          close-issue-message: "Closed. Even forgotten things must fade… unless it's about Hinata."
          days-before-stale: 7
          days-before-close: 3
